type: google.api.Service
config_version: 3

name: bookstore.endpoints.wahyudotdev-research.cloud.goog

title: Bookstore gRPC API
apis:
  - name: bookstore.BookStoreService
  - name: cart.CartService

usage:
  rules:
    # ListShelves methods can be called without an API Key.
    - selector: bookstore.BookStoreService.GetBook
      allow_unregistered_calls: true

    - selector: bookstore.BookStoreService.CreateBook
      allow_unregistered_calls: true

    - selector: cart.CartService.AddToCart
      allow_unregistered_calls: true

    - selector: cart.CartService.GetCart
      allow_unregistered_calls: true
