version: '3.9'

services:
  envoy:
    image: envoyproxy/envoy:tools-v1.26-latest
    container_name: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/api_descriptor.pb:/etc/envoy/api_descriptor.pb
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info" ]

  bookstore-service:
    build: bookstore-service
    environment:
      PORT: "3000"

  cart-service:
    build: cart-service
    container_name: cart-service
    environment:
      PORT: "3000"

  auth-service:
    build: auth-service
    environment:
      PORT: "3000"