version: '3.9'

services:
  bookstore-esp:
    image: gcr.io/endpoints-release/endpoints-runtime:2
    command:
      - --service=bookstore.endpoints.wahyudotdev-research.cloud.goog
      - --rollout_strategy=managed
      - --backend=grpc://bookstore:3000
      - --listener_port=8080
      - --non_gcp
      - --service_account_key=/keys/service-account-key.json
    ports:
      - "8080:8080"
    volumes:
      - ./keys:/keys

  bookstore:
    build: bookstore-service
    environment:
      PORT: 3000

  cart-esp:
    image: gcr.io/endpoints-release/endpoints-runtime:2
    command:
      - --service=bookstore.endpoints.wahyudotdev-research.cloud.goog
      - --rollout_strategy=managed
      - --backend=grpc://cart:3000
      - --listener_port=8080
      - --non_gcp
      - --service_account_key=/keys/service-account-key.json
    ports:
      - "8081:8080"
    volumes:
      - ./keys:/keys

  cart:
    build: cart-service
    environment:
      PORT: 3000