swagger: "2.0"
info:
  title: Bookstore gRPC API
  version: "1.0"
basePath: "/v1"
schemes:
  - "http"
host: "bookstore.endpoints.wahyudotdev-research.cloud.goog"

x-google-endpoints:
  - name: "bookstore.endpoints.wahyudotdev-research.cloud.goog"
    target: "35.232.6.24"

paths:
  /books:
    get:
      description: "Get books list"
      operationId: "GetBook"
      responses:
        200:
          description: "success"
    post:
      description: "Create book"
      operationId: "CreateBook"
      responses:
        200:
          description: "success"