apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    name: bookstore-service
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-service
spec:
  selector:
    matchLabels:
      name: bookstore-service
  template:
    metadata:
      labels:
        name: bookstore-service
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-account-key
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2
          args: [
            "--service=bookstore.endpoints.wahyudotdev-research.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://localhost:3000",
            "--listener_port=8080",
            "--non_gcp",
            "--service_account_key=/var/secrets/google/key.json"
          ]
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
        - name: bookstore
          image: wahyudotdev/bookstore-grpc
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    name: cart-service
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  selector:
    matchLabels:
      name: cart-service
  template:
    metadata:
      labels:
        name: cart-service
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-account-key
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2
          args: [
            "--service=bookstore.endpoints.wahyudotdev-research.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://localhost:3000",
            "--listener_port=8080",
            "--non_gcp",
            "--service_account_key=/var/secrets/google/key.json"
          ]
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
        - name: cart
          image: wahyudotdev/cart-grpc
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000